name: Build and Test on macos

on: [push, pull_request]

jobs:
  build-macos:

    name: Python (${{ matrix.python-version }})
    runs-on: macos-latest

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: >
        conda install
                      c-compiler
                      gfortran
                      nceplibs-ip
                      ninja
                      numpy
                      pip
                      setuptools
    - name: Install with pip
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        #pytest
