name: Build and Test on Windows

on: [push, pull_request]

jobs:
  build-windows:

    name: Python (${{ matrix.python-version }})
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python (Conda)
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
        activate-environment: test

    - name: Install conda dependencies
      run: |
        conda install c-compiler m2w64-gcc-fortran m2w64-gcc-libs nceplibs-g2c nceplibs-ip ninja numpy pip setuptools

    - name: Install with pip
      run: |
        pip install .

    - name: Test with pytest
      run: |
        python --version
        #pytest
