name: Build and Test on macos

on: [push, pull_request]

jobs:
  build-macos:

    name: Python (${{ matrix.python-version }})
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create environment
      shell: bash -l {0}
      run: |
        conda init bash
        conda create --name base${{ matrix.python-version }} python=${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Activate the base environment
        conda activate base${{ matrix.python-version }}
        conda install -c conda-forge setuptools nceplibs-ip numpy clang gfortran ninja pip
    - name: Install with pip
      shell: bash -l {0}
      run: |
        # Activate the base environment
        conda activate base${{ matrix.python-version }}
        pip install .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        # Activate the base environment
        conda activate base${{ matrix.python-version }}
        conda install pytest
        #pytest
